"""Builds a provenance table for every bundled ``data/*.json``: where each
table's symbol IDENTITY came from, where its VALUES came from, and which
caveats the file itself declares.

Why this exists: the paper separates assumption from finding, so every
number it quotes has to be traceable to one of a few clearly different
kinds of source. Those distinctions are already written into each JSON's
own ``_meta`` block (the project's standing rule: a generated table states
its own provenance). This script collects them into one table instead of
leaving them scattered across eight files, and checks them.

**The layer classification is rule-based and shows its work.** Each file's
value-layer is decided by the first matching rule in ``_VALUE_LAYER_RULES``,
and the report prints the exact ``_meta`` substring that triggered it -- so
the classification can be checked, not merely trusted. A file whose
``_meta`` matches no rule is reported as UNDECLARED rather than guessed at.

Layers, most to least directly sourced:

    AUTHORITATIVE  read straight out of an official ISWA artefact (the
                   Sutton font's cmap, @sutton-signwriting/core's symidArr).
                   No project judgment involved.
    MEASURED       computed from a published dataset by a documented
                   procedure (3d-hands-benchmark's MediaPipe estimates).
    DERIVED        deterministically derived from authoritative ISWA text
                   (a symbol's real name / the structure it states).
    AUTHORED       a human reading of the ISWA name, with no dataset behind
                   the specific numbers. Honest interpretation, not measurement.

Integrity checks run alongside: declared ``count`` vs. actual entries, the
declared ``generated_by`` script actually existing, and whether the file
declares any caveat at all.

Run:  python scripts/gen_provenance_table.py
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from fsw_r.core.iswa_data import category_of

DATA_DIR = Path(__file__).resolve().parent.parent / "src" / "fsw_r" / "data"
SCRIPTS_DIR = Path(__file__).resolve().parent
REPORT_DIR = Path(__file__).resolve().parent.parent / "reports"

_CATEGORY_NAME = {
    1: "Hands",
    2: "Movement",
    3: "Dynamics",
    4: "Head & Face",
    5: "Trunk & Limb",
    6: "Location",
    7: "Punctuation",
}

# ``_meta`` keys that describe where the symbol IDENTITY (which ISWA symbol
# this row is) came from, versus where its VALUES came from. Kept as
# explicit lists because the eight files grew their own key names over
# time; an unrecognised key shows up in "other_meta_keys" rather than being
# silently dropped.
_IDENTITY_KEYS = ("names_source", "source", "fills_source")
_VALUE_KEYS = ("values_source", "method", "structure_source", "source", "layer", "format")
_CAVEAT_KEYS = (
    "limitation",
    "unverified_assumptions",
    "fill_nuance",
    "fill_rotation_note",
    "rotation_note",
    "deferred",
    "default_bases",
    "note",
)

# First match wins. Ordered most-specific to least: an explicit AUTHORED
# marker outranks the fact that the same file's NAMES came from an
# authoritative source.
_VALUE_LAYER_RULES: tuple[tuple[str, str], ...] = (
    ("AUTHORED", "AUTHORED"),
    ("3d-hands-benchmark", "MEASURED"),
    ("derived directly from those verified names", "DERIVED"),
    ("generated by formula", "DERIVED"),
    ("@sutton-signwriting", "AUTHORITATIVE"),
)

_LAYER_ORDER = {"AUTHORITATIVE": 0, "MEASURED": 1, "DERIVED": 2, "AUTHORED": 3, "UNDECLARED": 4}


@dataclass(frozen=True)
class FileProvenance:
    filename: str
    entries: int
    categories: tuple[int, ...]
    identity_source: str
    value_source: str
    value_layer: str
    layer_evidence: str
    caveats: tuple[str, ...]
    generated_by: str
    declared_count: int | None
    count_matches: bool | None
    generator_exists: bool
    other_meta_keys: tuple[str, ...]


def _first(meta: dict[str, object], keys: tuple[str, ...]) -> tuple[str, str]:
    """First present key among ``keys`` -> (key, its text)."""
    for key in keys:
        if key in meta:
            return key, str(meta[key])
    return "", ""


def _classify(meta: dict[str, object]) -> tuple[str, str]:
    """(layer, the substring that decided it). Searches every value-ish
    ``_meta`` field, so a caveat buried in one field still counts."""
    haystack = " || ".join(f"{k}: {v}" for k, v in meta.items())
    for needle, layer in _VALUE_LAYER_RULES:
        index = haystack.find(needle)
        if index != -1:
            start = max(0, index - 40)
            return layer, "..." + haystack[start : index + len(needle) + 60].replace("\n", " ") + "..."
    return "UNDECLARED", ""


def _categories_of_keys(payload: dict[str, object]) -> tuple[int, ...]:
    """Which ISWA categories this file actually covers -- measured from its
    own base_hex keys, not from what ``_meta`` claims."""
    categories: set[int] = set()
    for key in payload:
        if key == "_meta":
            continue
        try:
            categories.add(category_of(int(key, 16)))
        except (ValueError, KeyError):
            continue
    return tuple(sorted(categories))


def collect() -> list[FileProvenance]:
    rows: list[FileProvenance] = []
    for path in sorted(DATA_DIR.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        meta_raw = payload.get("_meta")
        meta: dict[str, object] = meta_raw if isinstance(meta_raw, dict) else {}
        entries = len(payload) - (1 if meta else 0)

        _, identity = _first(meta, _IDENTITY_KEYS)
        value_key, value = _first(meta, _VALUE_KEYS)
        layer, evidence = _classify(meta)
        caveats = tuple(key for key in _CAVEAT_KEYS if key in meta)

        declared = meta.get("count") or meta.get("total_entries") or meta.get("total_base_symbols")
        declared_count = int(declared) if isinstance(declared, int) else None
        generated_by = str(meta.get("generated_by", ""))
        generator_name = Path(generated_by).name
        known = set(_IDENTITY_KEYS) | set(_VALUE_KEYS) | set(_CAVEAT_KEYS) | {
            "count",
            "total_entries",
            "total_base_symbols",
            "generated_by",
        }

        rows.append(
            FileProvenance(
                filename=path.name,
                entries=entries,
                categories=_categories_of_keys(payload),
                identity_source=identity,
                value_source=value if value_key else "",
                value_layer=layer,
                layer_evidence=evidence,
                caveats=caveats,
                generated_by=generated_by,
                declared_count=declared_count,
                count_matches=(declared_count == entries) if declared_count is not None else None,
                generator_exists=bool(generator_name) and (SCRIPTS_DIR / generator_name).exists(),
                other_meta_keys=tuple(k for k in meta if k not in known),
            )
        )
    return rows


def _shorten(text: str, limit: int = 150) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 3] + "..."


def render_markdown(rows: list[FileProvenance]) -> str:
    lines: list[str] = []
    lines.append("# Data Provenance Table")
    lines.append("")
    lines.append(
        "One row per bundled `data/*.json`. **Value layer** is assigned by the "
        "rule table in `scripts/gen_provenance_table.py`, and the `_meta` substring "
        "that triggered each assignment is listed under *Classification evidence* "
        "so the label can be checked rather than trusted."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Data file | Entries | ISWA categories | Value layer | Caveats declared |")
    lines.append("|---|---:|---|---|---|")
    for row in sorted(rows, key=lambda r: (_LAYER_ORDER.get(r.value_layer, 9), r.filename)):
        cats = ", ".join(f"{c} {_CATEGORY_NAME[c]}" for c in row.categories) or "—"
        caveats = ", ".join(f"`{c}`" for c in row.caveats) or "**none**"
        lines.append(
            f"| `{row.filename}` | {row.entries:,} | {cats} | **{row.value_layer}** | {caveats} |"
        )
    lines.append("")
    counts = {layer: sum(1 for r in rows if r.value_layer == layer) for layer in _LAYER_ORDER}
    lines.append(
        "Layer totals: "
        + ", ".join(f"{layer} {counts[layer]}" for layer in _LAYER_ORDER if counts[layer])
        + "."
    )
    lines.append("")
    lines.append("## Integrity checks")
    lines.append("")
    lines.append("| Data file | Declared count | Actual entries | Match | Generator script present |")
    lines.append("|---|---:|---:|---|---|")
    for row in sorted(rows, key=lambda r: r.filename):
        declared = f"{row.declared_count:,}" if row.declared_count is not None else "—"
        match = "—" if row.count_matches is None else ("yes" if row.count_matches else "**NO**")
        gen = "yes" if row.generator_exists else f"**MISSING** (`{row.generated_by}`)"
        lines.append(f"| `{row.filename}` | {declared} | {row.entries:,} | {match} | {gen} |")
    lines.append("")
    lines.append("## Per-file detail")
    lines.append("")
    for row in sorted(rows, key=lambda r: r.filename):
        lines.append(f"### `{row.filename}`")
        lines.append("")
        lines.append(f"- **Value layer:** {row.value_layer}")
        if row.layer_evidence:
            lines.append(f"- **Classification evidence:** `{_shorten(row.layer_evidence, 200)}`")
        lines.append(f"- **Identity / names source:** {_shorten(row.identity_source) or '—'}")
        lines.append(f"- **Value source:** {_shorten(row.value_source) or '—'}")
        lines.append(f"- **Generated by:** `{row.generated_by or '—'}`")
        if row.caveats:
            lines.append(f"- **Caveat fields declared:** {', '.join(f'`{c}`' for c in row.caveats)}")
        else:
            lines.append("- **Caveat fields declared:** none")
        if row.other_meta_keys:
            lines.append(f"- Other `_meta` keys: {', '.join(f'`{k}`' for k in row.other_meta_keys)}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    rows = collect()
    report = {
        "_meta": {
            "purpose": (
                "traceability of every bundled data table to its source, for the "
                "assumption-vs-finding separation the paper requires"
            ),
            "layer_rules": [{"contains": n, "layer": layer} for n, layer in _VALUE_LAYER_RULES],
            "generated_by": "scripts/gen_provenance_table.py",
        },
        "files": [
            {
                "filename": r.filename,
                "entries": r.entries,
                "iswa_categories": list(r.categories),
                "value_layer": r.value_layer,
                "layer_evidence": r.layer_evidence,
                "identity_source": r.identity_source,
                "value_source": r.value_source,
                "caveats_declared": list(r.caveats),
                "generated_by": r.generated_by,
                "declared_count": r.declared_count,
                "count_matches": r.count_matches,
                "generator_exists": r.generator_exists,
                "other_meta_keys": list(r.other_meta_keys),
            }
            for r in rows
        ],
    }
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    json_path = REPORT_DIR / "provenance.json"
    md_path = REPORT_DIR / "provenance.md"
    with open(json_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
        f.write("\n")
    markdown = render_markdown(rows)
    with open(md_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(markdown)
    print(f"Wrote {json_path}")
    print(f"Wrote {md_path}\n")
    print(markdown)


if __name__ == "__main__":
    main()
