"""Builds a provenance table for every bundled ``data/*.json``: where each
table's symbol IDENTITY came from, where its VALUES came from, and which
caveats the file itself declares.

Why this exists: the paper separates assumption from finding, so every
number it quotes has to be traceable to one of a few clearly different
kinds of source. Those distinctions are already written into each JSON's
own ``_meta`` block (the project's standing rule: a generated table states
its own provenance). This script collects them into one table instead of
leaving them scattered across eight files, and checks them.

**The layer classification is rule-based and shows its work.** Each file's
value-layer is decided by the first matching rule in ``_VALUE_LAYER_RULES``,
and the report prints the exact ``_meta`` substring that triggered it -- so
the classification can be checked, not merely trusted. A file whose
``_meta`` matches no rule is reported as UNDECLARED rather than guessed at.

Layers, most to least directly sourced:

    REFERENCE  read straight out of an official ISWA artefact (the Sutton
               font's cmap or glyph outlines, @sutton-signwriting/core's
               symidArr, signbank.org's BaseSymbol tables). The VALUE
               involves no project judgment.
    MEASURED   computed from a published dataset by a documented procedure
               (3d-hands-benchmark's MediaPipe estimates).
    MAPPED     an official ISWA artefact put through an explicit project
               rule (movement_paths.json's name -> path_type keyword table,
               its glyph-size -> amplitude scaling). Deterministic and
               traceable, but the RULE is this project's.
    AUTHORED   a human reading, with no dataset or deterministic source
               behind the specific numbers. Honest interpretation, not
               measurement.

**Vocabulary note.** Several files' own ``_meta`` say ``layer: derived``
for what this table calls REFERENCE. That word is deliberately not reused
here, because movement_paths.json is *also* "derived" in its own wording
while being a different thing (MAPPED) -- and using one word for both is
what made this table unable to tell the pre-fix movement_paths.json (path
type from the GROUP name) from the post-fix one (from each symbol's own
name). Each file's verbatim ``layer:`` declaration is reported alongside
the inferred one, so neither vocabulary is silently overwritten.

Integrity checks run alongside: declared ``count`` vs. actual entries,
every script named in ``generated_by`` actually existing (some tables are
now built by a chain of them), and whether the file declares any caveat.

Run:  python scripts/gen_provenance_table.py
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from fsw_r.core.iswa_data import category_of

DATA_DIR = Path(__file__).resolve().parent.parent / "src" / "fsw_r" / "data"
SCRIPTS_DIR = Path(__file__).resolve().parent
REPORT_DIR = Path(__file__).resolve().parent.parent / "reports"

_CATEGORY_NAME = {
    1: "Hands",
    2: "Movement",
    3: "Dynamics",
    4: "Head & Face",
    5: "Trunk & Limb",
    6: "Location",
    7: "Punctuation",
}

# ``_meta`` keys that describe where the symbol IDENTITY (which ISWA symbol
# this row is) came from, versus where its VALUES came from. Kept as
# explicit lists because the eight files grew their own key names over
# time; an unrecognised key shows up in "other_meta_keys" rather than being
# silently dropped.
_IDENTITY_KEYS = ("names_source", "source", "fills_source")
_VALUE_KEYS = ("values_source", "method", "structure_source", "source", "layer", "format")
_CAVEAT_KEYS = (
    "limitation",
    "unverified_assumptions",
    "fill_nuance",
    "fill_rotation_note",
    "rotation_note",
    "deferred",
    "default_bases",
    "note",
)

# First match wins, as REGEXES (not plain substrings) because one real
# ``_meta`` says "NOT AUTHORED" -- a substring match on "AUTHORED" would
# label the most carefully-sourced Category 2 table as authored, the exact
# opposite of the truth. The negative lookbehind is why this table shows
# its evidence: a classifier you cannot check is a classifier you cannot use.
_VALUE_LAYER_RULES: tuple[tuple[str, str], ...] = (
    (r"keyword table|glyph size ratio", "MAPPED"),
    (r"(?<!NOT )AUTHORED", "AUTHORED"),
    (r"3d-hands-benchmark", "MEASURED"),
    (r"derived directly from those verified names|generated by formula", "MAPPED"),
    (r"@sutton-signwriting|signbank\.org", "REFERENCE"),
)

# Ordered most to least directly sourced. Deliberately does NOT reuse the
# bare word "derived": several data files' own ``_meta`` use ``layer:
# derived`` to mean "read out of a real ISWA reference artefact", which is
# REFERENCE here, while movement_paths.json's path_type is derived by
# running a project keyword table over such an artefact, which is MAPPED.
# Collapsing those two into one word is what made the pre-fix and post-fix
# movement_paths.json indistinguishable in an earlier version of this table.
_LAYER_ORDER = {"REFERENCE": 0, "MEASURED": 1, "MAPPED": 2, "AUTHORED": 3, "UNDECLARED": 4}


@dataclass(frozen=True)
class FileProvenance:
    filename: str
    entries: int
    categories: tuple[int, ...]
    identity_source: str
    value_source: str
    value_layer: str
    layer_evidence: str
    declared_layer: str
    caveats: tuple[str, ...]
    generated_by: str
    declared_count: int | None
    count_matches: bool | None
    missing_generators: tuple[str, ...]
    other_meta_keys: tuple[str, ...]


def _first(meta: dict[str, object], keys: tuple[str, ...]) -> tuple[str, str]:
    """First present key among ``keys`` -> (key, its text)."""
    for key in keys:
        if key in meta:
            return key, str(meta[key])
    return "", ""


def _classify(meta: dict[str, object]) -> tuple[str, str]:
    """(layer, the excerpt that decided it). Searches every ``_meta`` field,
    so a marker buried in one of them still counts."""
    haystack = " || ".join(f"{k}: {v}" for k, v in meta.items())
    for pattern, layer in _VALUE_LAYER_RULES:
        match = re.search(pattern, haystack)
        if match is not None:
            start = max(0, match.start() - 40)
            return layer, "..." + haystack[start : match.end() + 60].replace("\n", " ") + "..."
    return "UNDECLARED", ""


def _declared_layer(meta: dict[str, object]) -> str:
    """The file's OWN ``layer:`` declaration, verbatim, or "" if it has none.

    Reported alongside this script's inferred layer rather than instead of
    it: the two vocabularies differ (see ``_LAYER_ORDER``), and a file that
    declares nothing is a finding, not something to paper over."""
    return str(meta.get("layer", ""))


def _generator_scripts(generated_by: str) -> tuple[str, ...]:
    """Every ``scripts/*.py`` named in ``generated_by``. Some tables are now
    produced by a chain of scripts (name fetch -> glyph measure -> assemble),
    so this is a list, not one path."""
    return tuple(re.findall(r"scripts/[\w./-]+\.py", generated_by))


def _categories_of_keys(payload: dict[str, object]) -> tuple[int, ...]:
    """Which ISWA categories this file actually covers -- measured from its
    own base_hex keys, not from what ``_meta`` claims."""
    categories: set[int] = set()
    for key in payload:
        if key == "_meta":
            continue
        try:
            categories.add(category_of(int(key, 16)))
        except (ValueError, KeyError):
            continue
    return tuple(sorted(categories))


def collect() -> list[FileProvenance]:
    rows: list[FileProvenance] = []
    for path in sorted(DATA_DIR.glob("*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        meta_raw = payload.get("_meta")
        meta: dict[str, object] = meta_raw if isinstance(meta_raw, dict) else {}
        entries = len(payload) - (1 if meta else 0)

        _, identity = _first(meta, _IDENTITY_KEYS)
        value_key, value = _first(meta, _VALUE_KEYS)
        layer, evidence = _classify(meta)
        caveats = tuple(key for key in _CAVEAT_KEYS if key in meta)

        declared = meta.get("count") or meta.get("total_entries") or meta.get("total_base_symbols")
        declared_count = int(declared) if isinstance(declared, int) else None
        generated_by = str(meta.get("generated_by", ""))
        generators = _generator_scripts(generated_by)
        known = set(_IDENTITY_KEYS) | set(_VALUE_KEYS) | set(_CAVEAT_KEYS) | {
            "count",
            "total_entries",
            "total_base_symbols",
            "generated_by",
        }

        rows.append(
            FileProvenance(
                filename=path.name,
                entries=entries,
                categories=_categories_of_keys(payload),
                identity_source=identity,
                value_source=value if value_key else "",
                value_layer=layer,
                layer_evidence=evidence,
                declared_layer=_declared_layer(meta),
                caveats=caveats,
                generated_by=generated_by,
                declared_count=declared_count,
                count_matches=(declared_count == entries) if declared_count is not None else None,
                missing_generators=tuple(
                    g for g in generators if not (SCRIPTS_DIR / Path(g).name).exists()
                ),
                other_meta_keys=tuple(k for k in meta if k not in known),
            )
        )
    return rows


def _shorten(text: str, limit: int = 150) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 3] + "..."


def render_markdown(rows: list[FileProvenance]) -> str:
    lines: list[str] = []
    lines.append("# Data Provenance Table")
    lines.append("")
    lines.append(
        "One row per bundled `data/*.json`. **Value layer** is assigned by the "
        "rule table in `scripts/gen_provenance_table.py`, and the `_meta` substring "
        "that triggered each assignment is listed under *Classification evidence* "
        "so the label can be checked rather than trusted."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Data file | Entries | ISWA categories | Value layer | Caveats declared |")
    lines.append("|---|---:|---|---|---|")
    for row in sorted(rows, key=lambda r: (_LAYER_ORDER.get(r.value_layer, 9), r.filename)):
        cats = ", ".join(f"{c} {_CATEGORY_NAME[c]}" for c in row.categories) or "—"
        caveats = ", ".join(f"`{c}`" for c in row.caveats) or "**none**"
        lines.append(
            f"| `{row.filename}` | {row.entries:,} | {cats} | **{row.value_layer}** | {caveats} |"
        )
    lines.append("")
    counts = {layer: sum(1 for r in rows if r.value_layer == layer) for layer in _LAYER_ORDER}
    lines.append(
        "Layer totals: "
        + ", ".join(f"{layer} {counts[layer]}" for layer in _LAYER_ORDER if counts[layer])
        + "."
    )
    lines.append("")
    lines.append("## Integrity checks")
    lines.append("")
    lines.append("| Data file | Declared count | Actual entries | Match | Generator script present |")
    lines.append("|---|---:|---:|---|---|")
    for row in sorted(rows, key=lambda r: r.filename):
        declared = f"{row.declared_count:,}" if row.declared_count is not None else "—"
        match = "—" if row.count_matches is None else ("yes" if row.count_matches else "**NO**")
        gen = "yes" if not row.missing_generators else "**MISSING** " + ", ".join(
            f"`{g}`" for g in row.missing_generators
        )
        lines.append(f"| `{row.filename}` | {declared} | {row.entries:,} | {match} | {gen} |")
    lines.append("")
    lines.append("## Per-file detail")
    lines.append("")
    for row in sorted(rows, key=lambda r: r.filename):
        lines.append(f"### `{row.filename}`")
        lines.append("")
        lines.append(f"- **Value layer:** {row.value_layer}")
        if row.layer_evidence:
            lines.append(f"- **Classification evidence:** `{_shorten(row.layer_evidence, 200)}`")
        lines.append(f"- **Identity / names source:** {_shorten(row.identity_source) or '—'}")
        lines.append(f"- **Value source:** {_shorten(row.value_source) or '—'}")
        lines.append(f"- **Generated by:** `{row.generated_by or '—'}`")
        if row.caveats:
            lines.append(f"- **Caveat fields declared:** {', '.join(f'`{c}`' for c in row.caveats)}")
        else:
            lines.append("- **Caveat fields declared:** none")
        if row.other_meta_keys:
            lines.append(f"- Other `_meta` keys: {', '.join(f'`{k}`' for k in row.other_meta_keys)}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    rows = collect()
    report = {
        "_meta": {
            "purpose": (
                "traceability of every bundled data table to its source, for the "
                "assumption-vs-finding separation the paper requires"
            ),
            "layer_rules": [{"contains": n, "layer": layer} for n, layer in _VALUE_LAYER_RULES],
            "generated_by": "scripts/gen_provenance_table.py",
        },
        "files": [
            {
                "filename": r.filename,
                "entries": r.entries,
                "iswa_categories": list(r.categories),
                "value_layer": r.value_layer,
                "layer_evidence": r.layer_evidence,
                "identity_source": r.identity_source,
                "value_source": r.value_source,
                "caveats_declared": list(r.caveats),
                "generated_by": r.generated_by,
                "declared_count": r.declared_count,
                "count_matches": r.count_matches,
                "missing_generators": list(r.missing_generators),
                "declared_layer": r.declared_layer,
                "other_meta_keys": list(r.other_meta_keys),
            }
            for r in rows
        ],
    }
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    json_path = REPORT_DIR / "provenance.json"
    md_path = REPORT_DIR / "provenance.md"
    with open(json_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
        f.write("\n")
    markdown = render_markdown(rows)
    with open(md_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(markdown)
    print(f"Wrote {json_path}")
    print(f"Wrote {md_path}\n")
    print(markdown)


if __name__ == "__main__":
    main()
