"""Generates ``src/fsw_r/data/movement_paths.json`` for all 242 Category 2
(Movement) base symbols from a small (group -> path_type/plane/is_hit)
table, NOT gathered from a per-symbol dataset the way Category 1's
``hand_joint_poses.json`` was.

Why formula, not measurement: Category 2's 10 groups are not 10
independent hand shapes the way Category 1's are -- they are the product
of two orthogonal axes, ``path_type`` (5 values) x ``plane`` (3 values, or
none for a few groups). Group NAMES (source: ISWA Manual Chapter 2) state
this directly -- e.g. "Curves Hit Floor Plane" = path_type CURVED, plane
FLOOR, is_hit True. So instead of gathering/measuring 242 independent
entries, this script derives all of them from 10 rows of table + the real
group boundaries already in ``core/iswa_data.py``'s ``GROUP_START``
(re-verified here, not re-hardcoded).

** UNVERIFIED ASSUMPTIONS ** -- also recorded in the generated JSON's own
``_meta`` and in PROGRESS.md's Phase 2 entry, not silently treated as fact:
- ``plane`` for groups 11 (Contact), 12 (Finger Movement), and 20
  (Circles) isn't stated by their group names the way groups 13-19's are
  -- left as ``None`` here; ``core/movement_paths.py`` decides what to do
  with that at render time (currently: fall back to WALL).
- ``is_hit`` is carried through as a flag; it has no geometric meaning
  implemented yet.
- ``curvature``/``amplitude``/``repeat`` are constant per path_type across
  an entire group -- there is currently no known source for how
  individual base symbols *within* one group actually differ from each
  other (ISWA presumably encodes that difference somehow -- e.g. small
  vs. large curve, single vs. double hump -- but it hasn't been identified
  yet, so every symbol in a group gets the same default).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from fsw_r.core.iswa_data import GROUP_START, symbol_id_of  # noqa: E402

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "src" / "fsw_r" / "data" / "movement_paths.json"

EXPECTED_TOTAL = 242

# Global group number (11-20, from core/iswa_data.py's GROUP_START indices
# 10-19) -> (real name, path_type, plane, is_hit). Names from ISWA Manual
# Chapter 2; path_type/plane/is_hit are this project's own reading of what
# each name implies (see module docstring).
_GROUP_TABLE: dict[int, tuple[str, str, str | None, bool]] = {
    11: ("Contact", "contact", None, False),
    12: ("Finger Movement", "finger", None, False),
    13: ("Straight Wall Plane", "straight", "wall", False),
    14: ("Straight Diagonal Plane", "straight", "diagonal", False),
    15: ("Straight Floor Plane", "straight", "floor", False),
    16: ("Curves Wall Plane", "curved", "wall", False),
    17: ("Curves Hit Wall Plane", "curved", "wall", True),
    18: ("Curves Hit Floor Plane", "curved", "floor", True),
    19: ("Curves Floor Plane", "curved", "floor", False),
    20: ("Circles", "circle", None, False),
}

# Constant per path_type -- see the "unverified assumptions" note above.
_DEFAULT_AMPLITUDE = 10.0
_DEFAULT_CURVATURE_BY_PATH_TYPE = {
    "straight": 0.0,
    "curved": 0.3,
    "circle": 0.0,
    "contact": 0.0,
    "finger": 0.0,
}
_DEFAULT_REPEAT = 1


def main() -> None:
    entries: dict[str, object] = {}
    for group in range(11, 21):
        group_name, path_type, plane, is_hit = _GROUP_TABLE[group]
        start = GROUP_START[group - 1]
        end = GROUP_START[group] - 1  # inclusive
        for base_hex in range(start, end + 1):
            key = format(base_hex, "x")
            entries[key] = {
                "symbol_id": symbol_id_of(base_hex),
                "group_name": group_name,
                "path_type": path_type,
                "plane": plane,
                "curvature": _DEFAULT_CURVATURE_BY_PATH_TYPE[path_type],
                "amplitude": _DEFAULT_AMPLITUDE,
                "repeat": _DEFAULT_REPEAT,
                "is_hit": is_hit,
            }

    if len(entries) != EXPECTED_TOTAL:
        raise RuntimeError(f"expected {EXPECTED_TOTAL} entries, got {len(entries)}")

    output = {
        "_meta": {
            "source": (
                "ISWA Manual Chapter 2 (group names) + this project's own "
                "(path_type, plane, is_hit) derivation from those names -- "
                "see core/movement_paths.py's docstring and PROGRESS.md's "
                "Phase 2 entry"
            ),
            "method": (
                "generated by formula from a 10-row (group -> path_type/"
                "plane/is_hit) table, NOT measured from any per-symbol "
                "dataset (unlike Category 1's hand_joint_poses.json, which "
                "came from real photographed hand poses)"
            ),
            "unverified_assumptions": [
                "plane for groups 11 (Contact), 12 (Finger Movement), 20 "
                "(Circles) is not stated by the group name; stored as null, "
                "core/movement_paths.py falls back to WALL at render time",
                "is_hit's exact geometric/rendering meaning is not "
                "implemented yet -- it is currently just a carried-through flag",
                "curvature/amplitude/repeat are constant per path_type/group, "
                "not derived from base_symbol_number -- how individual "
                "symbols within a group actually differ from each other is "
                "not yet known",
            ],
            "count": EXPECTED_TOTAL,
            "generated_by": "scripts/gen_movement_paths.py",
        },
        **entries,
    }
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"Wrote {len(entries)} entries to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
